/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
 const quranReflectVersions = require("./docs/quranreflect_versioned/versions.json");
 const quranDotComVersions = require("./docs/quran.com_versioned/versions.json");
 const {
   versionSelector,
   versionCrumb,
 } = require("docusaurus-plugin-openapi-docs/lib/sidebars/utils");

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{type: 'autogenerated', dirName: 'tutorial'}],
  APIsSidebar: [
    {
      type: "html",
      value: `<p style="color: var(--ifm-color-secondary-darkest)">DOCUMENTATION</p>`, // The HTML to be rendered
      defaultStyle: true, // Use the default menu item styling
    },
  ],
  "quranreflect": [
    {
      type: "html",
      defaultStyle: true,
      value: versionSelector(quranReflectVersions),
      className: "version-button",
    },
    {
      type: "html",
      defaultStyle: true,
      value: versionCrumb(`v1.0.0`),
    },
    {
      type: "category",
      label: "Quranreflect",
      link: {
        type: "generated-index",
        title: "Quranreflect API (latest)",
        description:"QuranReflect's APIs",
        slug: "/category/quranreflect-api",
      },
      items: require("./docs/quranreflect_versioned/sidebar.js"),
    },
  ],
  "quranreflect-1.0.0": [
    {
      type: "html",
      defaultStyle: true,
      value: versionSelector(quranReflectVersions),
      className: "version-button",
    },
    {
      type: "html",
      defaultStyle: true,
      value: versionCrumb(`v1.0.0`),
    },
    {
      type: "category",
      label: "Quranreflect",
      link: {
        type: "generated-index",
        title: "Quranreflect API (v1.0.0)",
        description:"QuranReflect's APIs",
        slug: "/category/quranreflect-api-1.0.0",
      },
      items: require("./docs/quranreflect_versioned/1.0.0/sidebar.js"),
    },
  ],
  "quran.com": [
    {
      type: "html",
      defaultStyle: true,
      value: versionSelector(quranDotComVersions),
      className: "version-button",
    },
    {
      type: "html",
      defaultStyle: true,
      value: versionCrumb(`v4.0.0`),
    },
    {
      type: "category",
      label: "quran.com",
      link: {
        type: "generated-index",
        title: "quran.com API (latest)",
        description:"quran.com's APIs",
        slug: "/category/quran.com-api",
      },
      items: require("./docs/quran.com_versioned/sidebar.js"),
    },
  ],
  "quran.com-4.0.0": [
    {
      type: "html",
      defaultStyle: true,
      value: versionSelector(quranDotComVersions),
      className: "version-button",
    },
    {
      type: "html",
      defaultStyle: true,
      value: versionCrumb(`v4.0.0`),
    },
    {
      type: "category",
      label: "quran.com",
      link: {
        type: "generated-index",
        title: "quran.com API (v4.0.0)",
        description:"quran.com's APIs",
        slug: "/category/quran.com-api-4.0.0",
      },
      items: require("./docs/quran.com_versioned/4.0.0/sidebar.js"),
    },
  ],
};

module.exports = sidebars;
