/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const quranDotComVersions = require("./docs/content_apis_versioned/versions.json");
const authVersions = require("./docs/user_related_apis_versioned/versions.json");
const {
  versionSelector,
  versionCrumb,
} = require("docusaurus-plugin-openapi-docs/lib/sidebars/utils");

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'tutorials'
    }
  ],
  APIsSidebar: [
    {
      type: "html",
      value: `<p style="color: var(--ifm-color-secondary-darkest)">DOCUMENTATION</p>`, // The HTML to be rendered
      defaultStyle: true, // Use the default menu item styling
    },
  ],
  "content-apis": [
    {
      type: "html",
      defaultStyle: true,
      value: versionSelector(quranDotComVersions),
      className: "version-button",
    },
    {
      type: "html",
      defaultStyle: true,
      value: versionCrumb(`v4.0.0`),
    },
    {
      type: "category",
      label: "Content APIs",
      link: {
        type: "generated-index",
        title: "Content APIs (latest)",
        description: "Content APIs",
        slug: "/category/content-apis",
      },
      items: require("./docs/content_apis_versioned/sidebar.js"),
    },
  ],
  "content-apis-4.0.0": [
    {
      type: "html",
      defaultStyle: true,
      value: versionSelector(quranDotComVersions),
      className: "version-button",
    },
    {
      type: "html",
      defaultStyle: true,
      value: versionCrumb(`v4.0.0`),
    },
    {
      type: "category",
      label: "Content APIs",
      link: {
        type: "generated-index",
        title: "Quran.Foundation Content API (v4.0.0)",
        description: "Content APIs",
        slug: "/category/content-apis-4.0.0",
      },
      items: require("./docs/content_apis_versioned/4.0.0/sidebar.js"),
    },
  ],
  "user-related-apis": [
    {
      type: "html",
      defaultStyle: true,
      value: versionSelector(authVersions),
      className: "version-button",
    },
    {
      type: "html",
      defaultStyle: true,
      value: versionCrumb(`v1.0.0`),
    },
    {
      type: "category",
      label: "User-related APIs",
      link: {
        type: "generated-index",
        title: "User-related (latest)",
        description: "User-related APIs",
        slug: "/category/user-related-apis",
      },
      items: require("./docs/user_related_apis_versioned/sidebar.js"),
    },
    {
      type: "doc",
      label: "Scopes",
      id: "user_related_apis_versioned/scopes",
    },
  ],
  "user-related-apis-1.0.0": [
    {
      type: "html",
      defaultStyle: true,
      value: versionSelector(authVersions),
      className: "version-button",
    },
    {
      type: "html",
      defaultStyle: true,
      value: versionCrumb(`v1.0.0`),
    },
    {
      type: "category",
      label: "User-related APIs",
      link: {
        type: "generated-index",
        title: "User-related APIs (v1.0.0)",
        description: "User-related APIs",
        slug: "/category/user-related-apis-1.0.0",
      },
      items: require("./docs/user_related_apis_versioned/1.0.0/sidebar.js"),
    },
    {
      type: "doc",
      label: "Scopes",
      id: "user_related_apis_versioned/scopes",
    },
  ],
};

module.exports = sidebars;
