/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const contentAPIsVersions = require("./docs/content_apis_versioned/versions.json");
const userRelatedAPIsVersions = require("./docs/user_related_apis_versioned/versions.json");
const oauth2APIsVersions = require("./docs/oauth2_apis_versioned/versions.json");
const {
  versionSelector,
  versionCrumb,
} = require("docusaurus-plugin-openapi-docs/lib/sidebars/utils");

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // 👇 Add this new block
  gettingStartedSidebar: [
    {
      type: "doc",
      id: "quickstart/index", // This points to /docs/quickstart/index.md
      label: "🚀 Quick Start Guide",
    },
  ],

  scopesSidebar: [
    {
      type: "doc",
      label: "OAuth2 Scopes",
      id: "user_related_apis_versioned/scopes",
    },
  ],
  tutorialsSidebar: [
    "tutorials/faq",
    {
      type: "autogenerated",
      dirName: "tutorials/oidc",
    },
  ],
  APIsSidebar: [
    {
      type: "doc",
      id: "quickstart/index", // ✅ Add here too if needed in sidebar
      label: "🚀 Quick Start Guide",
    },

    // {
    //   type: "html",
    //   value: `<p style="color: var(--ifm-color-secondary-darkest)">DOCUMENTATION</p>`, // The HTML to be rendered
    //   defaultStyle: true, // Use the default menu item styling
    // },
  ],
  "content-apis": [
    {
      type: "html",
      defaultStyle: true,
      value: versionSelector(contentAPIsVersions),
      className: "version-button",
    },
    {
      type: "html",
      defaultStyle: true,
      value: versionCrumb(`v4.0.0`),
    },
    {
      type: "category",
      label: "Content APIs",
      link: {
        type: "generated-index",
        title: "Content APIs (latest)",
        description: "Content APIs",
        slug: "/category/content-apis",
      },
      items: require("./docs/content_apis_versioned/sidebar.js"),
    },
  ],
  "content-apis-4.0.0": [
    {
      type: "html",
      defaultStyle: true,
      value: versionSelector(contentAPIsVersions),
      className: "version-button",
    },
    {
      type: "html",
      defaultStyle: true,
      value: versionCrumb(`v4.0.0`),
    },
    {
      type: "category",
      label: "Content APIs",
      link: {
        type: "generated-index",
        title: "Quran.Foundation Content API (v4.0.0)",
        description: "Content APIs",
        slug: "/category/content-apis-4.0.0",
      },
      items: require("./docs/content_apis_versioned/4.0.0/sidebar.js"),
    },
  ],
  "user-related-apis": [
    {
      type: "html",
      defaultStyle: true,
      value: versionSelector(userRelatedAPIsVersions),
      className: "version-button",
    },
    {
      type: "html",
      defaultStyle: true,
      value: versionCrumb(`v1.0.0`),
    },
    {
      type: "category",
      label: "User-related APIs",
      link: {
        type: "generated-index",
        title: "User-related (latest)",
        description: "User-related APIs",
        slug: "/category/user-related-apis",
      },
      items: require("./docs/user_related_apis_versioned/sidebar.js"),
    },
  ],
  "user-related-apis-1.0.0": [
    {
      type: "html",
      defaultStyle: true,
      value: versionSelector(userRelatedAPIsVersions),
      className: "version-button",
    },
    {
      type: "html",
      defaultStyle: true,
      value: versionCrumb(`v1.0.0`),
    },
    {
      type: "category",
      label: "User-related APIs",
      link: {
        type: "generated-index",
        title: "User-related APIs (v1.0.0)",
        description: "User-related APIs",
        slug: "/category/user-related-apis-1.0.0",
      },
      items: require("./docs/user_related_apis_versioned/1.0.0/sidebar.js"),
    },
  ],
  oauth2_apis: [
    {
      type: "html",
      defaultStyle: true,
      value: versionSelector(oauth2APIsVersions),
      className: "version-button",
    },
    {
      type: "html",
      defaultStyle: true,
      value: versionCrumb(`v1.0.0`),
    },
    {
      type: "category",
      label: "OAuth2 APIs",
      link: {
        type: "generated-index",
        title: "OAuth2 APIs (latest)",
        description: "OAuth2 APIs APIs",
        slug: "/category/oauth2_apis",
      },
      items: require("./docs/oauth2_apis_versioned/sidebar.js"),
    },
  ],
  "oauth2_apis-1.0.0": [
    {
      type: "html",
      defaultStyle: true,
      value: versionSelector(oauth2APIsVersions),
      className: "version-button",
    },
    {
      type: "html",
      defaultStyle: true,
      value: versionCrumb(`v1.0.0`),
    },
    {
      type: "category",
      label: "OAuth2 APIs",
      link: {
        type: "generated-index",
        title: "OAuth2 APIs (v1.0.0)",
        description: "OAuth2 APIs",
        slug: "/category/oauth2_apis-1.0.0",
      },
      items: require("./docs/oauth2_apis_versioned/1.0.0/sidebar.js"),
    },
  ],
};

module.exports = sidebars;
